=== rzvpop/MovieRental/clientsDB.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT clients (client*)>
<!ELEMENT client (name, email, movieList)>
<!ATTLIST client id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT movieList (movie*)>
<!ELEMENT movie (#PCDATA)>

=== rzvpop/MovieRental/clientsDB.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE clients PUBLIC "clientsDB.dtd" "clientsDB.dtd">
<clients><client id="10"><name>svd</name><email>65</email><movieList><movie>20</movie><movie>10</movie></movieList></client><client id="20"><name>drt</name><email>24</email><movieList><movie>20</movie></movieList></client><client id="1"><name>herbalife</name><age>8</age><movieList/></client></clients>
